baseURL = "http://example.org/"
languageCode = "en-us"
title = "Calaiswood"
theme = "responsive-horizontal"
[taxonomies]
	tag="tags"
	category="categories"

	[menu]
	[[menu.main]]
		name="L'association"
		identifier="asso"
		url="/apropos"
		hasChildren=true
		weight=1
	[[menu.main]]
		name="Projets"
		identifier="projets"
		url="/projets"
		weight=2
	[[menu.main]]
		name="Calaiswood Boulevard"
		identifier="boulevard"
		url="/calaiswoodboulevard"
		weight=3
	[[menu.main]]
		name="Participer"
		identifier="participer"
		url="/participer"
		weight=4

	[[menu.main]]
		name="A propos"
		identifier="apropos"
		url=""
		parent="asso"
		weight=1
	[[menu.main]]
		name="Qui sommes nous?"
		identifier="qui"
		url=""
		parent="asso"
		weight=1
	[[menu.main]]
		name="Partenaires et soutiens"
		identifier="partenaires"
		url=""
		parent="asso"
		weight=1
	
	[[menu.main]]
		name="Use-It"
		identifier="useit"
		url=""
		parent="projets"
		weight=1